//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostScadaCore.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IReportManagerService")]
    public interface IReportManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetAlarmsWithinPeriod", ReplyAction="http://tempuri.org/IReportManagerService/GetAlarmsWithinPeriodResponse")]
        ScadaCore.TriggeredAlarm[] GetAlarmsWithinPeriod(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetAlarmsWithinPeriod", ReplyAction="http://tempuri.org/IReportManagerService/GetAlarmsWithinPeriodResponse")]
        System.Threading.Tasks.Task<ScadaCore.TriggeredAlarm[]> GetAlarmsWithinPeriodAsync(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetAlarmsOfPriority", ReplyAction="http://tempuri.org/IReportManagerService/GetAlarmsOfPriorityResponse")]
        ScadaCore.TriggeredAlarm[] GetAlarmsOfPriority(int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetAlarmsOfPriority", ReplyAction="http://tempuri.org/IReportManagerService/GetAlarmsOfPriorityResponse")]
        System.Threading.Tasks.Task<ScadaCore.TriggeredAlarm[]> GetAlarmsOfPriorityAsync(int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetTagValues", ReplyAction="http://tempuri.org/IReportManagerService/GetTagValuesResponse")]
        ScadaCore.TagValue[] GetTagValues(string tagName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetTagValues", ReplyAction="http://tempuri.org/IReportManagerService/GetTagValuesResponse")]
        System.Threading.Tasks.Task<ScadaCore.TagValue[]> GetTagValuesAsync(string tagName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetLastValuesOfTags", ReplyAction="http://tempuri.org/IReportManagerService/GetLastValuesOfTagsResponse")]
        ScadaCore.TagValue[] GetLastValuesOfTags(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetLastValuesOfTags", ReplyAction="http://tempuri.org/IReportManagerService/GetLastValuesOfTagsResponse")]
        System.Threading.Tasks.Task<ScadaCore.TagValue[]> GetLastValuesOfTagsAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetTagValuesWithinPeriod", ReplyAction="http://tempuri.org/IReportManagerService/GetTagValuesWithinPeriodResponse")]
        ScadaCore.TagValue[] GetTagValuesWithinPeriod(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManagerService/GetTagValuesWithinPeriod", ReplyAction="http://tempuri.org/IReportManagerService/GetTagValuesWithinPeriodResponse")]
        System.Threading.Tasks.Task<ScadaCore.TagValue[]> GetTagValuesWithinPeriodAsync(System.DateTime start, System.DateTime end);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportManagerServiceChannel : HostScadaCore.ServiceReference1.IReportManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportManagerServiceClient : System.ServiceModel.ClientBase<HostScadaCore.ServiceReference1.IReportManagerService>, HostScadaCore.ServiceReference1.IReportManagerService {
        
        public ReportManagerServiceClient() {
        }
        
        public ReportManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ScadaCore.TriggeredAlarm[] GetAlarmsWithinPeriod(System.DateTime start, System.DateTime end) {
            return base.Channel.GetAlarmsWithinPeriod(start, end);
        }
        
        public System.Threading.Tasks.Task<ScadaCore.TriggeredAlarm[]> GetAlarmsWithinPeriodAsync(System.DateTime start, System.DateTime end) {
            return base.Channel.GetAlarmsWithinPeriodAsync(start, end);
        }
        
        public ScadaCore.TriggeredAlarm[] GetAlarmsOfPriority(int priority) {
            return base.Channel.GetAlarmsOfPriority(priority);
        }
        
        public System.Threading.Tasks.Task<ScadaCore.TriggeredAlarm[]> GetAlarmsOfPriorityAsync(int priority) {
            return base.Channel.GetAlarmsOfPriorityAsync(priority);
        }
        
        public ScadaCore.TagValue[] GetTagValues(string tagName) {
            return base.Channel.GetTagValues(tagName);
        }
        
        public System.Threading.Tasks.Task<ScadaCore.TagValue[]> GetTagValuesAsync(string tagName) {
            return base.Channel.GetTagValuesAsync(tagName);
        }
        
        public ScadaCore.TagValue[] GetLastValuesOfTags(string type) {
            return base.Channel.GetLastValuesOfTags(type);
        }
        
        public System.Threading.Tasks.Task<ScadaCore.TagValue[]> GetLastValuesOfTagsAsync(string type) {
            return base.Channel.GetLastValuesOfTagsAsync(type);
        }
        
        public ScadaCore.TagValue[] GetTagValuesWithinPeriod(System.DateTime start, System.DateTime end) {
            return base.Channel.GetTagValuesWithinPeriod(start, end);
        }
        
        public System.Threading.Tasks.Task<ScadaCore.TagValue[]> GetTagValuesWithinPeriodAsync(System.DateTime start, System.DateTime end) {
            return base.Channel.GetTagValuesWithinPeriodAsync(start, end);
        }
    }
}
