//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrendingApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITrendingProcessing")]
    public interface ITrendingProcessing {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrendingProcessing/GetInputTagValue", ReplyAction="http://tempuri.org/ITrendingProcessing/GetInputTagValueResponse")]
        string GetInputTagValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrendingProcessing/GetInputTagValue", ReplyAction="http://tempuri.org/ITrendingProcessing/GetInputTagValueResponse")]
        System.Threading.Tasks.Task<string> GetInputTagValueAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrendingProcessingChannel : TrendingApp.ServiceReference1.ITrendingProcessing, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrendingProcessingClient : System.ServiceModel.ClientBase<TrendingApp.ServiceReference1.ITrendingProcessing>, TrendingApp.ServiceReference1.ITrendingProcessing {
        
        public TrendingProcessingClient() {
        }
        
        public TrendingProcessingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrendingProcessingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingProcessingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingProcessingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetInputTagValue() {
            return base.Channel.GetInputTagValue();
        }
        
        public System.Threading.Tasks.Task<string> GetInputTagValueAsync() {
            return base.Channel.GetInputTagValueAsync();
        }
    }
}
